spring:
  application:
    name: lab4

  datasource:
    url: 'jdbc:postgresql://postgres:5432/mydb'
    username: 'postgres'
    password: 'password'
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none

  data:
    mongodb:
      uri: 'mongodb://root:password@mongodb:27017/mydb?authSource=admin'

  flyway:
    enabled: true
    locations: 'classpath:db/migration'

  docker:
    compose:
      lifecycle-management: start_only