CREATE SCHEMA IF NOT EXISTS LAB4_IPZWZ_SCHEMA;

CREATE TABLE LAB4_IPZWZ_SCHEMA.Viewer (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    age INT NOT NULL,
    gender VARCHAR(10) NOT NULL
);

CREATE TABLE LAB4_IPZWZ_SCHEMA.Ticket (
    id SERIAL PRIMARY KEY,
    date DATE NOT NULL,
    time TIME NOT NULL,
    seat_number VARCHAR(10) NOT NULL,
    movie_name VARCHAR(255) NOT NULL
);

CREATE TABLE LAB4_IPZWZ_SCHEMA.Orders (
    id SERIAL PRIMARY KEY,
    viewer_id INT REFERENCES LAB4_IPZWZ_SCHEMA.Viewer(id) NOT NULL,
    ticket_id INT REFERENCES LAB4_IPZWZ_SCHEMA.Ticket(id) NOT NULL,
    order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UQ_ORDERS_V_T UNIQUE (viewer_id, ticket_id)
);